/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cmd.DownThread;
import com.jcraft.jsch.JSch;
import com.jcraft.jsch.JSchException;
import instance.Instance_data;
import instance.Instance_hold;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JRootPane;

/**
 *
 * @author RobsonP
 */
public class PasswordDiagRSA extends JDialog {

    String uname;
    byte[] privatek;
    byte[] publick;
    JSch jsch;
    /**
     * Creates new form PasswordFrame
     */
    public PasswordDiagRSA() {
        initComponents();
        this.setVisible(false);
        this.setModal(true);
       
        this.setLocation((int)(Instance_hold.getMframe().getLocation().getX()+Instance_hold.getMframe().getSize().getWidth()/2-this.getSize().getWidth()/2), (int)(Instance_hold.getMframe().getLocation().getY()+Instance_hold.getMframe().getSize().getHeight()/2-this.getSize().getHeight()/2));
        this.setTitle("Authentication");
        this.setIconImage(new ImageIcon(getClass().getResource("/gui/design/logo_small.jpg")).getImage());
        
        JRootPane rootPane = this.getRootPane();
        rootPane.setDefaultButton(this.jButton_OK);
        
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_passphrase = new javax.swing.JLabel();
        jPasswordField_passphrase = new javax.swing.JPasswordField();
        jButton_OK = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel_passphrase.setText("Passphrase for Key");

        jButton_OK.setText("OK");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_cancel.setText("cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_cancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_passphrase)
                        .addComponent(jPasswordField_passphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_passphrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_passphrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OK)
                    .addComponent(jButton_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        Instance_hold.getSh_mon().setCancel(true);
        
        DownThread dt = new DownThread();
        dt.start();
 
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        Instance_hold.getMframe().toFront();
        StringBuffer strbuf = new StringBuffer("");
        
        strbuf.append(this.jPasswordField_passphrase.getPassword());
        Instance_data.setRsakeypw(strbuf.toString());
        
        try {
            jsch.addIdentity(uname, privatek, publick , strbuf.toString().getBytes());
        } catch (JSchException ex) {
            Logger.getLogger(PasswordDiagRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Instance_hold.getSh().setPasswordcheck(true);
        this.jPasswordField_passphrase.setText("");
        this.dispose();
    }//GEN-LAST:event_jButton_OKActionPerformed

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public byte[] getPrivatek() {
        return privatek;
    }

    public void setPrivatek(byte[] privatek) {
        this.privatek = privatek;
    }

    public byte[] getPublick() {
        return publick;
    }

    public void setPublick(byte[] publick) {
        this.publick = publick;
    }

    public JSch getJsch() {
        return jsch;
    }

    public void setJsch(JSch jsch) {
        this.jsch = jsch;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JLabel jLabel_passphrase;
    private javax.swing.JPasswordField jPasswordField_passphrase;
    // End of variables declaration//GEN-END:variables
}