/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import instance.Instance_data;
import instance.Instance_hold;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.border.TitledBorder;

/**
 *
 * @author RobsonP
 */
public class SettingsDiag extends JDialog {
    
    /**
     * Creates new form SettingsFrame
     */
    public SettingsDiag() {
        initComponents();
         
        this.setTitle("Settings");
        this.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/gui/design/logo_small.jpg")).getImage());
        this.setLocation((int)Instance_hold.getMframe().getLocation().getX()+(int)(Instance_hold.getMframe().getSize().getWidth()/3), (int)Instance_hold.getMframe().getLocation().getY()+(int)(Instance_hold.getMframe().getSize().getHeight()/5));

        TitledBorder title;
        title = BorderFactory.createTitledBorder("Optional");
        this.jPanel_optional.setBorder(title);
    
        this.pack();
        
        this.getRootPane().setDefaultButton(jButton_ok);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Settings = new javax.swing.JPanel();
        jButton_export = new javax.swing.JButton();
        jLabel_uname = new javax.swing.JLabel();
        jTextField_uname = new javax.swing.JTextField();
        jLabel_tmp = new javax.swing.JLabel();
        jTextField_tmp = new javax.swing.JTextField();
        jButton_browse_tmp = new javax.swing.JButton();
        jLabel_server = new javax.swing.JLabel();
        jTextField_server = new javax.swing.JTextField();
        jLabel_port = new javax.swing.JLabel();
        jTextField_port = new javax.swing.JTextField();
        jButton_cancel = new javax.swing.JButton();
        jPanel_optional = new javax.swing.JPanel();
        jLabel_RSA = new javax.swing.JLabel();
        jTextField_RSA = new javax.swing.JTextField();
        jButton_browse_keyfile = new javax.swing.JButton();
        jLabel_keyfile_desc = new javax.swing.JLabel();
        jButton_ok = new javax.swing.JButton();
        jButton_import = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        KeyStroke keyExport = KeyStroke.getKeyStroke(KeyEvent.VK_E, Event.ALT_MASK);
        Action performExport = new AbstractAction("Export") {
            public void actionPerformed(ActionEvent e) {
                //do your save
                JFileChooser fc = new JFileChooser();
                fc.setVisible(true);
                FC_sav_Listener listener = new FC_sav_Listener();
                listener.setJfc(fc);
                fc.addActionListener(listener);
                fc.showSaveDialog(Instance_hold.getSetframe());
            }
        };

        jButton_export.getActionMap().put("performExport", performExport);
        jButton_export.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyExport, "performExport");

        jButton_export.setMnemonic('E');
        jButton_export.setText("Export");
        jButton_export.setName("sssec"); // NOI18N
        jButton_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exportActionPerformed(evt);
            }
        });

        jLabel_uname.setText("Username:");

        jLabel_tmp.setText("Path of Temp-Folder:");

        jButton_browse_tmp.setText("browse");
        jButton_browse_tmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browse_tmpActionPerformed(evt);
            }
        });

        jLabel_server.setText("Server:");

        jLabel_port.setText("Port:");

        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jLabel_RSA.setText("Keyfile:");

        jButton_browse_keyfile.setText("browse");
        jButton_browse_keyfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browse_keyfileActionPerformed(evt);
            }
        });

        jLabel_keyfile_desc.setText("(private key for OpenSSH RSA)");

        javax.swing.GroupLayout jPanel_optionalLayout = new javax.swing.GroupLayout(jPanel_optional);
        jPanel_optional.setLayout(jPanel_optionalLayout);
        jPanel_optionalLayout.setHorizontalGroup(
            jPanel_optionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionalLayout.createSequentialGroup()
                .addComponent(jLabel_keyfile_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_browse_keyfile))
            .addGroup(jPanel_optionalLayout.createSequentialGroup()
                .addComponent(jLabel_RSA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_optionalLayout.setVerticalGroup(
            jPanel_optionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_optionalLayout.createSequentialGroup()
                .addGroup(jPanel_optionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_RSA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_optionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_browse_keyfile)
                    .addComponent(jLabel_keyfile_desc)))
        );

        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        KeyStroke keyImport = KeyStroke.getKeyStroke(KeyEvent.VK_I, Event.ALT_MASK);
        Action performImport = new AbstractAction("Import") {
            public void actionPerformed(ActionEvent e) {
                //do your save
                JFileChooser fc = new JFileChooser();
                fc.setVisible(true);
                FC_load_Listener listener = new FC_load_Listener();
                listener.setJfc(fc);
                listener.setSetdiag(Instance_hold.getSetframe());
                fc.addActionListener(listener);
                fc.showOpenDialog(Instance_hold.getSetframe());
            }
        };

        jButton_import.getActionMap().put("performImport", performImport);
        jButton_import.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyImport, "performImport");

        jButton_import.setMnemonic('I');
        jButton_import.setText("Import");
        jButton_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_importActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SettingsLayout = new javax.swing.GroupLayout(jPanel_Settings);
        jPanel_Settings.setLayout(jPanel_SettingsLayout);
        jPanel_SettingsLayout.setHorizontalGroup(
            jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_optional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SettingsLayout.createSequentialGroup()
                        .addComponent(jLabel_tmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jTextField_tmp, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SettingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_browse_tmp))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SettingsLayout.createSequentialGroup()
                        .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                                .addComponent(jLabel_server)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_server))
                            .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_cancel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_import, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                                .addComponent(jLabel_port)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_uname)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel_SettingsLayout.setVerticalGroup(
            jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel_optional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_tmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_browse_tmp)
                .addGap(18, 18, 18)
                .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_server)
                    .addComponent(jTextField_server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_port)
                    .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton_import)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_export)
                    .addComponent(jButton_ok)
                    .addComponent(jButton_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_SettingsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_uname)
                        .addComponent(jTextField_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(318, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_browse_keyfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browse_keyfileActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setVisible(true);
        FC_RSA_Listener listener = new FC_RSA_Listener();
        listener.setJfc(fc);
        fc.addActionListener(listener);
        fc.showOpenDialog(null);
    }//GEN-LAST:event_jButton_browse_keyfileActionPerformed

    private void jButton_browse_tmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browse_tmpActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setVisible(true);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        FC_tmp_Listener listener = new FC_tmp_Listener();
        listener.setJfc(fc);
        fc.addActionListener(listener);
        fc.showOpenDialog(null);
    }//GEN-LAST:event_jButton_browse_tmpActionPerformed

    private void jButton_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exportActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setVisible(true);
        FC_sav_Listener listener = new FC_sav_Listener();
        listener.setJfc(fc);
        fc.addActionListener(listener);
        fc.showSaveDialog(this);
    }//GEN-LAST:event_jButton_exportActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        Instance_data.setUname(this.jTextField_uname.getText());
        
        if (this.jTextField_RSA.getText().equals("")) {
            Instance_data.setRsakeyPath("EMPTY");
        } else {
            Instance_data.setRsakeyPath(this.jTextField_RSA.getText());
        }
        
        Instance_data.setTmpPath(this.jTextField_tmp.getText());
        Instance_hold.getMframe().getjTextField_Server().setText(this.jTextField_server.getText());
        
        if (this.jTextField_port.getText().equals("")) {
            Instance_hold.getMframe().getjTextField_Port().setText("22");
        } else {
            Instance_hold.getMframe().getjTextField_Port().setText(this.jTextField_port.getText());
        }
        
        this.setVisible(false);
        Instance_hold.getMframe().getjButton_connect().setEnabled(true);
        Instance_hold.getMframe().getjTextField_Server().setEnabled(true);
            Instance_hold.getMframe().getjTextField_Port().setEnabled(true);
        JOptionPane.showMessageDialog(null, "Settings loaded");
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jButton_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_importActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setVisible(true);
        FC_load_Listener listener = new FC_load_Listener();
        listener.setJfc(fc);
        listener.setSetdiag(this);
        fc.addActionListener(listener);
        fc.showOpenDialog(this);
    }//GEN-LAST:event_jButton_importActionPerformed

    public JTextField getjTextField_RSA() {
        return jTextField_RSA;
    }

    public void setjTextField_RSA(JTextField jTextField_RSA) {
        this.jTextField_RSA = jTextField_RSA;
    }

    public JTextField getjTextField_tmp() {
        return jTextField_tmp;
    }

    public void setjTextField_tmp(JTextField jTextField_tmp) {
        this.jTextField_tmp = jTextField_tmp;
    }

    public JTextField getjTextField_uname() {
        return jTextField_uname;
    }

    public void setjTextField_uname(JTextField jTextField_uname) {
        this.jTextField_uname = jTextField_uname;
    }

    public JTextField getjTextField_port() {
        return jTextField_port;
    }

    public void setjTextField_port(JTextField jTextField_port) {
        this.jTextField_port = jTextField_port;
    }

    public JTextField getjTextField_server() {
        return jTextField_server;
    }

    public void setjTextField_server(JTextField jTextField_server) {
        this.jTextField_server = jTextField_server;
    }

    /**
     * @param args the command line arguments
     */

    public JButton getjButton_import() {
        return jButton_import;
    } 

    public JButton getjButton_ok() {
        return jButton_ok;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_browse_keyfile;
    private javax.swing.JButton jButton_browse_tmp;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_export;
    private javax.swing.JButton jButton_import;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JLabel jLabel_RSA;
    private javax.swing.JLabel jLabel_keyfile_desc;
    private javax.swing.JLabel jLabel_port;
    private javax.swing.JLabel jLabel_server;
    private javax.swing.JLabel jLabel_tmp;
    private javax.swing.JLabel jLabel_uname;
    private javax.swing.JPanel jPanel_Settings;
    private javax.swing.JPanel jPanel_optional;
    private javax.swing.JTextField jTextField_RSA;
    private javax.swing.JTextField jTextField_port;
    private javax.swing.JTextField jTextField_server;
    private javax.swing.JTextField jTextField_tmp;
    private javax.swing.JTextField jTextField_uname;
    // End of variables declaration//GEN-END:variables
}